#!/bin/bash
set -euo pipefail


mysql -uroot -p"$MYSQL_ROOT_PASSWORD" <<EOF
CREATE DATABASE IF NOT EXISTS $CHESSDB_NAME;

CREATE USER IF NOT EXISTS '$CHESSDB_ADMIN_USER'@'%' IDENTIFIED WITH caching_sha2_password BY '$CHESSDB_ADMIN_PASS';
CREATE USER IF NOT EXISTS '$CHESSDB_ADMIN_USER'@'localhost' IDENTIFIED WITH caching_sha2_password BY '$CHESSDB_ADMIN_PASS';

GRANT ALL PRIVILEGES ON $CHESSDB_NAME.* TO '$CHESSDB_ADMIN_USER'@'%' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON $CHESSDB_NAME.* TO '$CHESSDB_ADMIN_USER'@'localhost' WITH GRANT OPTION;

CREATE USER IF NOT EXISTS '$CHESSDB_PUBLIC_USER'@'%' IDENTIFIED WITH caching_sha2_password BY '$CHESSDB_PUBLIC_PASS';
CREATE USER IF NOT EXISTS '$CHESSDB_PUBLIC_USER'@'localhost' IDENTIFIED WITH caching_sha2_password BY '$CHESSDB_PUBLIC_PASS';

GRANT SELECT ON $CHESSDB_NAME.* TO '$CHESSDB_PUBLIC_USER'@'%';
GRANT SELECT ON $CHESSDB_NAME.* TO '$CHESSDB_PUBLIC_USER'@'localhost';
EOF
