#version: "3.9"

services:

  mysql:
#    build:
#      context: .
#      dockerfile: Dockerfile.mysql
    image: dpuiu2/chess_web-mysql:2.0
#    image: ghcr.io/dpuiu/chess_web-mysql:2.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      CHESSDB_NAME: ${CHESSDB_NAME}
      CHESSDB_ADMIN_USER: ${CHESSDB_ADMIN_USER}
      CHESSDB_ADMIN_PASS: ${CHESSDB_ADMIN_PASS}
      CHESSDB_PUBLIC_USER: ${CHESSDB_PUBLIC_USER}
      CHESSDB_PUBLIC_PASS: ${CHESSDB_PUBLIC_PASS}
      CHESSDB_BACKUP_URL: ${CHESSDB_BACKUP_URL}
    ports:
      - "${MYSQL_PORT}:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-p$${MYSQL_ROOT_PASSWORD}"]
      interval: 20s
      timeout: 20s
      retries: 5
      start_period: 120s
#    tmpfs:
#      - /tmp:size=1G

  public:
#    build:
#      context: .
#      dockerfile: Dockerfile.public
    image: dpuiu2/chess_web-public:2.0
#    image: ghcr.io/dpuiu/chess_web-public:2.0
    depends_on:
      mysql:
        condition: service_healthy
    command: ["/opt/venv/bin/gunicorn", "-w", "${GUNICORN_WORKERS:-4}", "-b", "0.0.0.0:5000", "--timeout", "600", "--log-level", "debug", "--access-logfile", "-", "--error-logfile", "-", "app_public:app"]
    environment:
      CHESSDB_HOST: mysql
      CHESSDB_NAME: ${CHESSDB_NAME}
      CHESSDB_USER: ${CHESSDB_PUBLIC_USER}
      CHESSDB_PASS: ${CHESSDB_PUBLIC_PASS}
      FLASK_DEBUG: 0
      FLASK_PUBLIC_PORT: ${FLASK_PUBLIC_PORT}
      CHESS_FRONTEND_DIST: /app/dist
      CORS_ALLOWED_ORIGINS: http://localhost:${FLASK_PUBLIC_PORT}
      CHESSAPP_DATA_URL: ${CHESSAPP_DATA_URL}
    ports:
      - "${FLASK_PUBLIC_PORT}:5000"
#    tmpfs:
#      - /tmp:size=1G
