FROM mysql:8.0

COPY ./my_custom.cnf /etc/mysql/conf.d/my_custom.cnf
COPY ./CHESSApp_DB/chess.db.schema.mysql.sql /docker-entrypoint-initdb.d/db_init_1.sql
COPY ./db_init.sh /docker-entrypoint-initdb.d/db_init_2.sh
COPY ./db_load.sh /docker-entrypoint-initdb.d/db_init_3.sh

#RUN chmod +x /docker-entrypoint-initdb.d/db_init_2.sh
#CMD ["mysqld"]

EXPOSE 3306
