apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx
#  namespace: chess-web
  creationTimestamp: null
spec:
  ingressClassName: nginx
  rules:
#    - host: dev.sites.idies.jhu.edu
    - host: localhost
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: public
                port:
                  number: 80

          - path: /chess_app
            pathType: Prefix
            backend:
              service:
                name: public
                port:
                  number: 80

          - path: /health
            pathType: Prefix
            backend:
              service:
                name: public
                port:
                  number: 80

          - path: /middleware/stats
            pathType: Prefix
            backend:
              service:
                name: public
                port:
                  number: 80

