namespace: chess-web

mysql:
  replicaCount: 1
  image: docker.io/dpuiu2/chess_web-mysql:2.5
  adminPassword: your_admin_password
  adminUser: chess_admin
  dbName: CHESS_DB
  publicPassword: your_public_password
  publicUser: chess_public
  rootPassword: your_secure_password

public:
  replicaCount: 1
  image: docker.io/dpuiu2/chess_web-public:2.7
  corsOrigins: https://dev.sites.idies.jhu.edu
  flaskDebug: "0"
  flaskPublicPort: "5000"
  flaskAppRoot: /chess_app
  frontendDist: /app/dist

ingress:
  host: dev.sites.idies.jhu.edu

